### ISSUE TITLE
`let` sometimes interfere between individual specs

### ISSUE THREAD

**Issue by mspanc** [antonmi/espec#67] opened 2015-12-02 09:26 UTC
I am using espec 0.8.7.

I've found out that sometimes value defined as `let` in one context "leak" into another contexts in async specs. Below are two subsequent runs of exactly the same code, one fails, another passes.

The code is available here: https://github.com/mspanc/dbux/tree/031e4ddd8170a1c7f7421a72d7aaba8c86fa4d92

You can also use provided Vagrant environment if you want to have exactly the same test case.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mix espec
Compiled lib/value.ex
Compiled lib/message.ex
Generated dbux app
F.........................*...........................................*..*......................*.

	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value contains object path of invalid syntax
	/vagrant/spec/value_spec.exs:642
	Pending with message: but value contains object path of invalid syntax.


	2) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFE throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:636
	Temporarily skipped with: `xcontext`.


	3) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'string' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFE throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:567
	Temporarily skipped with: `xcontext`.


	4) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'signature' value that is invalid and represented as string but value contains signature of invalid syntax
	/vagrant/spec/value_spec.exs:707
	Pending with message: but value contains signature of invalid syntax.

	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'int32' value that is invalid and represented as integer but value is smaller than -0x80000000 throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:302
	** (MatchError) no match of right hand side value: nil
    spec/value_spec.exs:9: DBux.ValueSpec.endianness/0
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:865: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:407: :erl_eval.expr/5
    (elixir) src/elixir.erl:197: :elixir.erl_eval/3
    (elixir) src/elixir.erl:185: :elixir.eval_forms/4
    (elixir) lib/code.ex:157: Code.eval_quoted/3
    spec/value_spec.exs:5: DBux.ValueSpec.result/0


	98 examples, 1 failures, 4 pending

	Finished in 10.22 seconds (10.03s on load, 0.19s on specs)

	Randomized with seed 966486

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mix espec
....*...*..............*......*...................................................................

	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'string' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFE throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:567
	Temporarily skipped with: `xcontext`.


	2) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value contains object path of invalid syntax
	/vagrant/spec/value_spec.exs:642
	Pending with message: but value contains object path of invalid syntax.


	3) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'signature' value that is invalid and represented as string but value contains signature of invalid syntax
	/vagrant/spec/value_spec.exs:707
	Pending with message: but value contains signature of invalid syntax.


	4) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFE throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:636
	Temporarily skipped with: `xcontext`.

	98 examples, 0 failures, 4 pending

	Finished in 10.51 seconds (10.33s on load, 0.17s on specs)

	Randomized with seed 21176
```

**Comment by antonmi** [comment] 2015-12-02 09:49
Are you sure that 'let' cause the problem?
Is any 'global state' in your application? 
Try to replace 'let' with 'shared' dictionary using 'before' helper.

**Comment by mspanc** [comment] 2015-12-02 10:37
I don't have any 'global state'.

I am not sure if it's about let, but this is what is declared in the line mentioned in the stacktrace.

Maybe it's because first launch triggered compilation? Dunno.

**Comment by antonmi** [comment] 2015-12-02 10:44
Try to replace 'let' with 'shared' dictionary using 'before' helper.

**Comment by mspanc** [comment] 2015-12-02 10:57
It seems to be random: https://travis-ci.org/mspanc/dbux/jobs/94372563

I'll make such attempt later and let you know what is the outcome. But do you mean that such usage of let is improper or do you just want to check if that may be a workaround?

**Comment by antonmi** [comment] 2015-12-02 11:08
The usage is corrent. But 'let' is more complex because stored in separate agent while 'shared' dictionary simply pass through examples. So if problem disappear with 'shared' therefore 'let' is the reason.

**Comment by antonmi** [comment] 2015-12-02 11:11
And try to run your specs with the same seed. 781997 in the last example.

**Comment by mspanc** [comment] 2015-12-06 20:15
I hadn't checked let substitution with shared block yet, but I've noticed that with commit 7efaaf8c8ceb85b17702064e746432af6a335f91 of the repo mentioned before that I am able to reproduce the issue by passing certain seed.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mix espec --seed 938409
F.F...*.................................*...................................................**.......................

	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'string' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFF throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:621
	Temporarily skipped with: `xcontext`.


	2) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value contains object path of invalid syntax
	/vagrant/spec/value_spec.exs:770
	Pending with message: but value contains object path of invalid syntax.


	3) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'object_path' value that is invalid and represented as string but value's byte representation is longer than 0xFFFFFFFE throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:764
	Temporarily skipped with: `xcontext`.


	4) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'signature' value that is invalid and represented as string but value contains signature of invalid syntax
	/vagrant/spec/value_spec.exs:843
	Pending with message: but value contains signature of invalid syntax.

	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'int16' value that is invalid and represented as integer but value is smaller than -0x8000 throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:176
	** (MatchError) no match of right hand side value: nil
    spec/value_spec.exs:9: DBux.ValueSpec.endianness/0
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:865: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:407: :erl_eval.expr/5
    (elixir) src/elixir.erl:197: :elixir.erl_eval/3
    (elixir) src/elixir.erl:185: :elixir.eval_forms/4
    (elixir) lib/code.ex:157: Code.eval_quoted/3
    spec/value_spec.exs:5: DBux.ValueSpec.result/0



	2) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'uint32' value that is invalid and represented as integer but value is smaller than 0 throws {:badarg, :value, :outofrange}
	/vagrant/spec/value_spec.exs:365
	** (MatchError) no match of right hand side value: nil
    spec/value_spec.exs:9: DBux.ValueSpec.endianness/0
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:865: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:407: :erl_eval.expr/5
    (elixir) src/elixir.erl:197: :elixir.erl_eval/3
    (elixir) src/elixir.erl:185: :elixir.eval_forms/4
    (elixir) lib/code.ex:157: Code.eval_quoted/3
    spec/value_spec.exs:5: DBux.ValueSpec.result/0


	117 examples, 2 failures, 4 pending

	Finished in 20.0 seconds (19.73s on load, 0.27s on specs)

	Randomized with seed 938409
```

**Comment by mspanc** [comment] 2015-12-07 09:49
I've noticed that it is always about throwing matchers (when there's a `expect(fn -> ... end)` syntax).

**Comment by mspanc** [comment] 2015-12-07 09:52
I have also noticed that changing this code

```
  context ".marshall/2" do
    let :result, do: DBux.Value.marshall(%DBux.Value{type: type, value: value}, endianness)

    context "if passed 'byte' value" do
      let :type, do: :byte
      let :endianness, do: :little_endian
```

into this

```
  context ".marshall/2" do
    let :result, do: DBux.Value.marshall(%DBux.Value{type: type, value: value}, endianness)
    let :endianness, do: :little_endian

    context "if passed 'byte' value" do
      let :type, do: :byte
```

solves the issue.

Is that enough for suggesting where lies the issue? (refactoring to use shared instead of let will be quite time consuming so I want to do this as a last resort)

**Comment by antonmi** [comment] 2015-12-07 09:58
Marcin, thanks for the investigation.
I'm going to figure out the reason ASAP.

**Comment by antonmi** [comment] 2015-12-07 11:24
Hey, Marcin.
I've cloned your project and discovered that these two specs fail when run them individualy:
```sh
mix espec spec/value_spec.exs:176
1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'int16' value that is invalid and represented as integer but value is smaller than -0x8000 throws {:badarg, :value, :outofrange}
	/Users/antonmi/elixir/dbux/spec/value_spec.exs:176
	** (MatchError) no match of right hand side value: nil
    spec/value_spec.exs:9: DBux.ValueSpec.endianness/0
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:877: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
    (elixir) src/elixir.erl:196: :elixir.erl_eval/3
    (elixir) src/elixir.erl:184: :elixir.eval_forms/4
    (elixir) lib/code.ex:194: Code.eval_quoted/3
    spec/value_spec.exs:5: DBux.ValueSpec.result/0
```
```sh
mix espec spec/value_spec.exs:365
	1) DBux.ValueSpec DBux.ValueSpec .marshall/2 if passed 'uint32' value that is invalid and represented as integer but value is smaller than 0 throws {:badarg, :value, :outofrange}
	/Users/antonmi/elixir/dbux/spec/value_spec.exs:365
	** (MatchError) no match of right hand side value: nil
    spec/value_spec.exs:9: DBux.ValueSpec.endianness/0
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:877: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
    (elixir) src/elixir.erl:196: :elixir.erl_eval/3
    (elixir) src/elixir.erl:184: :elixir.eval_forms/4
    (elixir) lib/code.ex:194: Code.eval_quoted/3
    spec/value_spec.exs:5: DBux.ValueSpec.result/0
```

**Comment by antonmi** [comment] 2015-12-07 11:39
Ah, I see.
The `endianness` is not available in the scope of `spec/value_spec.exs:176`, so the test fails.
Of course, when you set `endianness` value in outer scope it becames available in inner scope and all specs became green.
The real issue is: How `endianness` appers it the `spec/value_spec.exs:176` when one run all specs.

**Comment by antonmi** [comment] 2015-12-07 12:06
Ok, I''ve found the root of the error.
'let' macros defines a function inside spec module. For example
```elixir 
let :endianness, do: :little_endian
```
defines `DBux.ValueSpec.endianness/0` function and keep the return value in the 'let dictionary'.
When you run `espec` all specs are executed in random order. So some spec may put its `endianness` value into the dictionary.

I'll try to fix the issue in the near future.

**Comment by antonmi** [comment] 2015-12-09 11:09
Hey, Marcin!
I'm afraid I won't fix the issue. Because I can't change the way 'let' works.
You should expicitely use 'let(:value)' in every scope where you use 'value'.

**Comment by mspanc** [comment] 2015-12-09 11:14
Well, it undermines the context of context nesting, isn't it? How does such spec tree differ from flat unit tests if I have to redefine lets in every context? Needless to say about DRY...

Is your position more like "I don't think it should work that way" or "it's too much work to reimplement this"? In the latter case maybe I can help somehow.

**Comment by antonmi** [comment] 2015-12-09 11:34
No, you don't need set it in every context. The value defined in outer scope will be accessible in inner scopes.
```elixir
context "c1" do
  let :a, do: 1
  context "c2" do
    it do: expect a |> to eq 1
  end
end
```
But in your specs there was (and is) a different situaiton. Something like this.
```elixir
context "top" do
  context "c1" do
    let :a, do: 1
    it do: expect a |> to eq 1
  end

  context "c2" do
    it do: expect a |> to eq 1  #you try to access a in this scope.
  end
end
```
Obviously there is no 'a' in "c2" context.

My position is "Your specs are not correct, so you have such unexpected behavior".

**Comment by mspanc** [comment] 2015-12-09 11:36
Ah ok, got it :)

**Comment by antonmi** [comment] 2015-12-09 11:37
Thanks!

**Comment by antonmi** [comment] 2016-04-02 09:00
The issue relates to "Leaking 'subject' issue" #89.

**Comment by antonmi** [comment] 2016-04-02 09:02
The #89 is fixed now.

**Closed** 2016-04-08 16:58 UTC
Labels: bug, duplicate, ready to close
