### ISSUE TITLE
Crash while mocking module from stdlib

### ISSUE THREAD

**Issue by mspanc** [antonmi/espec#42] opened 2015-09-09 13:07 UTC
I am trying to test code that basically looks like this

```elixir
defmodule MyApp.SomethingImportant.Supervisor do
  use Supervisor

  def start_link(options \\ []) do
    Supervisor.start_link(__MODULE__, options)
  end
end
```

I want to ensure that `start_link` really spawns supervisor process. So I write:

```elixir
defmodule MyApp.SomethingImportantTest do
  alias MyApp.SomethingImportant.Supervisor, as: This
  
  use ESpec, async: false

  context ".start_link/0" do
    before do
      allow(Supervisor).to accept(:start_link, fn(_, _) -> {:ok, self()} end)
    end

    it "calls Supervisor.start_link with MyApp.SomethingImportant.Supervisor as arg, passes [] as options and returns {:ok, pid}" do
      This.start_link

      expect(Supervisor).to accepted(:start_link, [])
    end
  end
end
```

This test should fail, because parameters passed to `accepted` are invalid but I even don't reach that stage because the VM crashes with:

```
** (EXIT from #PID<0.49.0>) {:compile_forms, {:error, [{'lib/supervisor.ex', [{459, :erl_lint, {:type_syntax, :integer}}, {459, :erl_lint, {:type_syntax, :integer}}, {459, :erl_lint, {:type_syntax, :integer}}, {459, :erl_lint, {:type_syntax, :integer}}]}], []}}
```

I was unable to find clear pattern what exactly causes this error.

Ubuntu 14.04 64-bit
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
Elixir 1.0.5
espec 0.7.0

**Comment by mspanc** [comment] 2015-09-09 14:34
I've downgraded erlang to 17.5.3 and the problem does not occur.

Here are commands to install both erlang and elixir in the versions that don't trigger the issue on ubuntu 14.04

```
      wget -O /tmp/erlang.tar.gz https://s3.amazonaws.com/s3.hex.pm/builds/erlang/cedar-14/OTP-17.5.3.tar.gz && mkdir -p /usr/local/erlang && tar xzvf /tmp/erlang.tar.gz -C /usr/local/erlang --strip-components=1 && /usr/local/erlang/Install -minimal /usr/local/erlang && echo "PATH=/usr/local/erlang/bin:\$PATH" > /etc/profile.d/erlang.sh && chmod +x /etc/profile.d/erlang.sh && rm /tmp/erlang.tar.gz
      wget -O /tmp/elixir.zip https://s3.amazonaws.com/s3.hex.pm/builds/elixir/v1.0.5.zip && mkdir -p /usr/local/elixir && cd /usr/local/elixir && unzip -q /tmp/elixir.zip && chmod +x /usr/local/elixir/bin/* && echo "PATH=/usr/local/elixir/bin:\$PATH" > /etc/profile.d/elixir.sh && chmod +x /etc/profile.d/elixir.sh && rm /tmp/elixir.zip
```

**Comment by mspanc** [comment] 2015-09-09 20:04
That may be useful: https://groups.google.com/forum/#!topic/elixir-lang-talk/oYXyvEUi64Y

**Comment by antonmi** [comment] 2015-09-10 09:49
Hi, Marcin!
I think the problem is deeper.
When you use `allow` espec creates mock with `meck`
```elixir
:meck.new(module, [:non_strict, :passthrough])
```
If you try run the code in console
```elixir
:meck.new(Supervisor, [:non_strict, :passthrough])
```
you will receive the same error.

So, we can address the issue to [eproxus/meck](https://github.com/eproxus/meck).
But in the [Caveats](https://github.com/eproxus/meck#caveats) they indicate:
"Since Erlang have a flat module namespace, replacing a module has to be done globally in the Erlang VM. This means certain modules cannot be mocked."

This might be an answer.

**Comment by mspanc** [comment] 2015-09-17 12:53
Please see Alexei's comments in the beforementioned thread:

```
Looks like allow(Supervisor).to expands to {ESpec.AllowTo, module}.to which no longer works in Erlang 18?
```

I am still not convinced if that is an issue in meck, as it is a compiler crash.

**Comment by antonmi** [comment] 2015-09-17 13:07
Alexei's statement is wrong. It does work in erlang 18

**Comment by antonmi** [comment] 2015-09-21 18:41
May I close the issue?

**Comment by mspanc** [comment] 2015-09-21 18:51
Well, I can't answer this. For me it crashes, I am still not capable of saying if it's an issue in espec or something else.

**Comment by skirino** [comment] 2015-10-26 13:56
Let me share our case.

Our project doesn't use espec but uses meck directly.
We have the following test failure (due to a compile error) when we simply use Precompiled.zip available [here](https://github.com/elixir-lang/elixir/releases):
```
** (EXIT from #PID<0.458.0>) {:compile_forms, {:error, [{'lib/system.ex', [{235, :erl_lint, {:type_syntax, :integer}}]}], [{'lib/system.ex', [{0, :erl_lint, {:unused_var, :cwd@1}}]}]}}
```

On the other hand when we use self-compiled elixir executable there's no problem.
I have no idea what's the difference, but if the behavior reported by @mspanc changes by switching elixir executable, this is neither espec's issue nor meck's.

Latest x86_64 Manjaro Linux & Amazon Linux
Erlang 18.1 (self-compiled using [kerl](https://github.com/yrashk/kerl))
Elixir v1.1.1

Hope this helps!

**Comment by antonmi** [comment] 2015-10-26 15:37
Thanks, Shunsuke.

**Comment by optikfluffel** [comment] 2015-11-13 12:21
I'm facing the same issue [when testing with Travis](https://travis-ci.org/optikfluffel/obelisk/jobs/90929957) with Elixir v1.1.1 and OTP 18.1 - [testing with other Elixir/OTP configurations](https://travis-ci.org/optikfluffel/obelisk/builds/90929953) works fine.

**Closed** 2016-02-17 17:53 UTC
Labels: ready to close
